### ISSUE TITLE
360加固后签名后安装不了

### ISSUE THREAD

**Issue by yyyofyr430** [LazyIonEs/AndroidToolKit#2]
Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]

**Comment by LazyIonEs** [comment]
目前工具内使用到的签名工具是有这个问题的，当开启了文件对齐后，并不能为签名apk进行文件对齐，可使用
```
zipalign -c -v 4 existing.apk
```
命令行进行检测。

目前[Apksig](https://mvnrepository.com/artifact/com.android.tools.build/apksig)已在`8.4.0-beta02`版本中修复了这个问题，但是我目前并不会去更新他，因为他现在还在测试中，等后续出现稳定版后我会及时的去更新他。

对于目前的问题，我推荐使用
```
zipalign -p -f -v 4 infile.apk outfile.apk
```
命令行对加固后的apk进行文件对齐后，在进行签名就可以了。

**Comment by Roby8023** [comment]
360加固后签名的问题, 可以再直接用360加固软件的签名功能(免费)就可以了. 我前段时间也遇到了, 可以参考这个帖子:
https://blog.csdn.net/SCHOLAR_II/article/details/134146657

**Comment by LazyIonEs** [comment]
1.4.2版本已修复此问题
