### ISSUE TITLE
Windows 平台 apk 文件路径包含中文时无法解析

### ISSUE THREAD

**Issue by dongfengweixiao** [LazyIonEs/AndroidToolKit#3]
如图，在 Windows 系统中，当 apk 的路径包含中文时（包括路径包含中文或者是 apk 文件名本身为中文），无法正确的解析 apk 的信息，仅能够显示文件的大小和 md5。

![image](https://github.com/LazyIonEs/AndroidToolKit/assets/1300822/4fba0fbe-c768-40a5-a116-47ba7f7d21ea)

**Comment by LazyIonEs** [comment]
可以在设置内修改下aapt的路径，指定到本机内为aapt2.exe的文件，后续我会在新版本修改默认的aapt版本以修复这个问题

**Comment by LazyIonEs** [comment]
> 谢谢，更换为aapt2后，可以正常解析了。
> 
> PS：介意我抄袭下你的ui吗，最近也正在写一个桌面端的apk解析工具，使用flutter作为前端，正在头疼ui怎么设计。

我并不介意，如果可以，遇到关于UI的问题，欢迎与我讨论，我深知一个人开发时UI对于项目重要性与难度，常常会陷于纠结之中
