### ISSUE TITLE
发行版增加 Linux 支持

### ISSUE THREAD

**Issue by dongfengweixiao** [LazyIonEs/AndroidToolKit#4]
可以考虑增加 TargetFormat.AppImage，TargetFormat.Deb，TargetFormat.Rpm 等支持，本地尝试编译为 TargetFormat.AppImage，经测试，运行正常。

**Comment by LazyIonEs** [comment]
后续会考虑增加，但我这边没有测试设备，没办法保证稳定性

**Comment by oiloveio** [comment]
作者，你好，反馈个问题，apk安装是中文名，但是apk信息内显示为英文名。

**Comment by LazyIonEs** [comment]
> 作者，你好，反馈个问题，apk安装是中文名，但是apk信息内显示为英文名。

可以开个新的Issues，如果可以，麻烦提供下apk文件

**Comment by LazyIonEs** [comment]
> > 作者，你好，反馈个问题，apk安装是中文名，但是apk信息内显示为英文名。
> 
> 这个很正常吧。因为aapt工具是读取的androidmanifest.xml中的内容。想要根据locale读取本地化的应用名称，需要再解析 resources.arsc，但是这一步 aapt 似乎并没有做。

会去找项目内所有地区的应用名称的，只是我做这个功能的时候只取了默认的名称，并没有取`application-label-zh-CN`
可以用`aapt dump badging file.apk`命令看一下打印出的内容`application-label`与`application-label-zh-CN`的值是否一致

**Comment by LazyIonEs** [comment]
> 可以考虑增加 TargetFormat.AppImage，TargetFormat.Deb，TargetFormat.Rpm 等支持，本地尝试编译为 TargetFormat.AppImage，经测试，运行正常。

麻烦发一份Linux的aapt2文件，谢谢，下个版本会支持

**Comment by LazyIonEs** [comment]
> 可以考虑增加 TargetFormat.AppImage，TargetFormat.Deb，TargetFormat.Rpm 等支持，本地尝试编译为 TargetFormat.AppImage，经测试，运行正常。

新版本已发，有空可以看一下，我这边没办法测试，不确定有没有问题
