### ISSUE TITLE
读取微信的 apk 信息失败

### ISSUE THREAD

**Issue by dongfengweixiao** [LazyIonEs/AndroidToolKit#5]
下载的 apk 的名称为 weixin8049android2600_0x2800313d_arm64.apk。
直接从 https://weixin.qq.com/ 下载。
表现为一直显示小飞机动画，无法加载出 apk 的信息。

**Comment by LazyIonEs** [comment]
> 下载的 apk 的名称为 weixin8049android2600_0x2800313d_arm64.apk。 直接从 https://weixin.qq.com/ 下载。 表现为一直显示小飞机动画，无法加载出 apk 的信息。

正在排查，初步判断是因为`bufferedReader.readLine()`没有返回值并阻塞导致，后续会修复

**Comment by LazyIonEs** [comment]
问题已解决，稍后会发布新版本
