### ISSUE TITLE
设置默认值后无法修改

### ISSUE THREAD

**Issue by xiangyao0906** [LazyIonEs/AndroidToolKit#6]
![image](https://github.com/user-attachments/assets/404e735a-4650-4a42-9ea2-03086141fa78)

![image](https://github.com/user-attachments/assets/b03c36a3-9168-458f-8fbb-536c7d4a4d39)

**Comment by LazyIonEs** [comment]
最近我正在增加新的功能，目前推上去的代码并不是完整的，最近等我测试完了之后会更新版本更新及修复

**Comment by LazyIonEs** [comment]
最新版已修复
